baseURL = 'http://example.org/'
title = 'Beauty Pointe'
theme = 'hugo-universal-theme'
languageCode = 'en-us'
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

summaryLength = 30

[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Blog"
    identifier = "menu.blog"
    url        = "/blog/"
    weight     = 2

[[menu.main]]
    name       = "Contact"
    identifier = "menu.contact"
    url        = "/contact/"
    weight     = 3

# TOP bar
[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+12 34 567 89 01"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 4
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:hello@beautypointe.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

# params
[params]
    viewMorePostLink = "/blog/"
    author = "JuanJuanZero"
    defaultKeywords = ["beauty", "salon", "nails", "wellness"]
    mainSections = ["blog"]

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "juanjuanzero" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = false

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "pink"

    about_us = "<p>At Beauty Pointe, value is not just a price point; it's the essence of our commitment to providing exceptional care that won't break the bank. We believe everyone deserves access to top-notch beauty and wellness services without compromise. Our affordable yet luxurious treatments are designed to make you look and feel your best without sacrificing quality.</p>"
    copyright = "Copyright (c) 2023, Beauty Pointe; all rights reserved."

    disabled_logo = true
    logo_text = "Beauty Pointe"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Beauty Pointe.</strong>
        <br>1234 New Avenue
        <br>Beauty City
        <br>901 665
        <br>United States
      </p>
      """
    
    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = false


[params.testimonials]
    enable = false

[params.see_more]
    enable = false

[params.clients]
    enable = false

[params.recent_posts]
    enable = true
    title = "Get to Know us"
    subtitle = "Discover a sanctuary where beauty meets well-being at Beauty Pointe. We go beyond the surface, offering a unique blend of pampering and holistic care. Our skilled team is dedicated to enhancing your natural radiance with affordable luxury. Come, explore Beauty Pointe, and let us redefine beauty as a journey of self-love and timeless transformation. Here's a few articles about us and what we are about."
    hide_summary = false

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

